#!/bin/bash
$ curl -X GET http://127.0.0.1:5984/developers/noah
$ curl -X GET http://127.0.0.1:5984/developers/adam

$ couchapp generate view ssh_public_keys
$ ls -A views/ssh_public_keys/
map.js    reduce.js
$ cat > views/ssh_public_keys/map.js <<EOF
function(doc) {
    if (doc.ssh_public_key) emit(doc.ssh_public_key, doc.ssh_public_key)
}
EOF
$ rm views/ssh_public_keys/reduce.js
$ couchapp push
$ curl -X GET http://127.0.0.1:5984/developers/_design/developers/_view/ssh_public_keys